version: '3.8'

services:
  web:
    build: .
    container_name: django-web
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      exec uwsgi --http 0.0.0.0:8000 --module parrotsite.wsgi:application --uid 1000 --gid 1000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: app
      DJANGO_DB_USER: worker
      DJANGO_DB_PASS: worker
      DJANGO_DB_PORT: "5432"
      DJANGO_DEBUG: "False"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: worker
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worker -d app"]
      interval: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
